services:
  - type: web
    name: piped-backend
    env: docker
    plan: free
    region: frankfurt
    envVars:
      - key: PORT
        value: 8080
      - key: HTTP_WORKERS
        value: 2
      - Key: DATABASE_URL
        Value: postgresql://ae:JlTweX71KtuA6SM9nUnMulByQhgV6NdC@dpg-d2vvq7fdiees738qnvr0-a/piped_fclz
