services:
  - type: web
    name: piped-backend
    env: docker
    plan: free
    region: frankfurt
    envVars:
      - key: PORT
        value: 8080
      - key: HTTP_WORKERS
        value: 2
      - Key: DATABASE_URL
        Value: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
