services:
  # This is the Piped Backend Web Service
  - type: web
    name: piped-backend
    env: docker
    plan: free # Note: Render free plans spin down after inactivity.
    region: frankfurt # Use the same region as your database for best performance
    healthCheckPath: /healthcheck
    envVars:
      # The 'fromDatabase' property tells Render to inject the connection string
      # from the database defined below. This is secure and automatic.
      - key: DATABASE_URL
        fromDatabase:
          name: piped-db # This must match the name of the database service below
          property: connectionString
      - key: INIT_DB
        value: true # Tells Piped to initialize the database schema on first start
      - key: REGISTRATION_ENABLED
        value: false # Set to 'true' if you want to allow user registrations
      - key: PROXY_PART_SIZES
        value: 5242880
      - key: UPLOAD_LIMITS_VIDEO
        value: 104857600
      - key: UPLOAD_LIMITS_AVATAR
        value: 1048576

# This defines the PostgreSQL Database
databases:
  - name: piped-db
    plan: free # Note: Render free databases are deleted after 90 days.
    region: frankfurt
