services:
  - type: web
    name: piped-backend
    env: docker
    plan: free
    region: frankfurt
    healthCheckPath: /healthcheck
    envVars:
      - key: hibernate.connection.url
        value: jdbc:postgresql://dpg-d301piodl3ps739mv5j0-a/piped_db_0mai
      - key: hibernate.connection.username
        value: piped_db_0mai_user
      - key: hibernate.connection.password
        value: EEIhp8Iyqi3MPNLEuEssohVIhNUAGK5H
      - key: PORT
        value: 10000 # This should match the Render $PORT if set, or use ${PORT}
      # ...other envVars as needed...

databases:
  - name: piped-db
    plan: free
    region: frankfurt
